services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/starter-kit
      - PORT=5001
    depends_on:
      - mongodb

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8082:80"
    depends_on:
      - backend

volumes:
  mongodb_data: