version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/starter-kit
      - PORT=5001
    depends_on:
      - mongodb

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongodb_data: