services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db

  server:
    build:
      context: server
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/starter-kit
      - PORT=5001
    depends_on:
      - mongodb

  client:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server

volumes:
  mongodb_data: